# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SinaWeibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SinaWeibo
  pod 'SnapKit', '~> 3.0'
  pod 'AFNetworking', '~> 3.1'
  pod 'SVProgressHUD', '~> 2.0'
  pod 'SDWebImage', '~> 3.8'
  pod 'YYModel', '~> 1.0'
  pod 'pop'
end
